package concurrency.ch7.cancel.exception;

import org.slf4j.LoggerFactory;

public class Testlog {

	public static void main(String[] args) {
		 LoggerFactory.getLogger(Testlog.class).error("test" );

	}

}
